### ISSUE TITLE
Client & Server 환경 설정

### ISSUE THREAD

**Issue by egaoneko** [egaoneko/stocker#21]
## Task

* [x] Next.js
* [x] Koa
* [x] ~Passport~ -> Firebase 적용으로 불필요
* [x] ~JWT~ -> Firebase 적용으로 불필요
* [x] Firebase Auth
* [x] Next.js with Koa for i18n
  * [x] next-i18n-next가 KOA를 미지원... 다국어가 필요하다면 그때 다시 시도....
* [x] Next.js with Mobx
