### ISSUE TITLE
User Modeling

### ISSUE THREAD

**Issue by egaoneko** [egaoneko/stocker#23]
## Reference

https://sequelize.org/master/identifiers.html
https://github.com/RobinBuschmann/sequelize-typescript

## Task

- [x] User entity 및 model 생성
- [x] User usecase, repostory and provider 생성
- [x] App Context 생성
